import sharp from 'sharp';
import { writeFileSync } from 'fs';

const SRC = 'images/race_track_mask.png';
const OUT = 'src/game/trackCollisionData.js';
const W = 256;
const H = 384;

async function main() {
  const { data } = await sharp(SRC)
    .resize(W, H, { fit: 'fill' })
    .ensureAlpha()
    .raw()
    .toBuffer({ resolveWithObject: true });

  // Pack into bitfield: 1 = track (red > green), 0 = wall
  const totalBits = W * H;
  const bytes = new Uint8Array(Math.ceil(totalBits / 8));

  for (let i = 0; i < totalBits; i++) {
    const pi = i * 4; // RGBA
    const r = data[pi];
    const g = data[pi + 1];
    const b = data[pi + 2];
    const a = data[pi + 3];
    // Track = white/opaque (high brightness + high alpha)
    // Wall = black OR transparent (low brightness OR low alpha)
    const isTrack = (a > 128 && (r + g + b) > 384) ? 1 : 0;
    if (isTrack) {
      bytes[i >> 3] |= (1 << (i & 7));
    }
  }

  // Encode as base64 for compact embedding
  const b64 = Buffer.from(bytes).toString('base64');

  const js = `// Auto-generated by scripts/process-mask.js — do not edit
export const COLLISION_W = ${W};
export const COLLISION_H = ${H};
export const COLLISION_DATA = Uint8Array.from(atob("${b64}"), c => c.charCodeAt(0));
`;

  writeFileSync(OUT, js);
  console.log(`Written ${OUT}: ${W}x${H} grid, ${bytes.length} bytes (${b64.length} chars b64)`);
}

main();
